<a href="https://colab.research.google.com/github/JaradAng/Classification-Project---Churn-Prediction/blob/main/00tensorflowfundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###Going to explore tensor fundamentals using TF
# Going to go over:
# intro to tensors
# info from tensors
# manipulating tensors
# tensors and numpy
# using @tf.function to speed up python functions
#use GPU with TF
#Few exercises


# Into to tensors

In [2]:
#import TF
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# creating a tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dims of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Checking vector dimensions
vector.ndim

1

In [ ]:
#Create a matrix(matrix has more than one dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# checking dimensions of the matrix
matrix.ndim

2

In [6]:
# specify the dtype of matrix
another_matrix = tf.constant([[10., 7.],
                              [3.,2.],
                              [8.,9.]], dtype =tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [7]:
#checkin dimensions 
another_matrix.ndim

2

In [10]:
#creating a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
#check dims
tensor.ndim

3

What we created so far

* scalar : a single number
* Vector is a number with direction like wind speed and direction
* matrix is a 2-dimensional array of numbers
tensor is an n-dimensional array of numbers (where n can be anynumber, a 0-dimensinoal tensor is a scaler, 1-dimensional tensor is a vector)


In [4]:
#using the same tensor but with tf variable
changeable_tensor = tf.Variable([10,7])

unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [6]:
#Trying to change element in changeable tensor
changeable_tensor[0] = 7

TypeError: ignored

In [7]:
#Trying .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [10]:
#lets try on the unchangeable
unchangeable_tensor[0].assign(7)

AttributeError: ignored

Unable to change if it is a constant. tf variable allows for a change

Note: Rarely will need to decide between the two but if in doubt use constant and change it later if needed

### next will be exploring random tensor creation. 

random tensors are some arbitrary size which contain random numbers


In [11]:
#Creating two (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # setting seed for reproducibility

random_1 = random_1.normal(shape=(3,2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
random_2 = tf.random.Generator.from_seed(42)

random_2 = random_2.normal(shape=(3,2))

random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [13]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of tensors elements

In [17]:
# Shuffle a tensor....valuable for when you want to shuffle your data so the inherent order doesn't effect learning

not_shuffled = tf.constant([[10, 7], [3,4], [2,5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [16]:
# shuffle the non shuffled tensor

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [24]:
# shuffle the non shuffled tensor
tf.random.set_seed(42) #Keeps the same order, global level seed

tf.random.shuffle(not_shuffled, seed= 42) #Still gets different results if did not have above becuase it is operation level

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

Everytime running the shuffle, it puts it in a different order. If you want shuffle tensors to be in the same order, we have to use the global level random seed as well as operation level random seed

### Creating tensors in other ways

In [25]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
#Create tensor of all zeros
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors
the main difference between numpy arrasy and tf tensors is that tensors can be run on a gpu. which makes it much faster

In [28]:
# you can also turn Numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)

numpy_A

#X = tf.constant(some_matrix)  capital for matrix for tensor
#y = tf.constant(some_vector) lower case ususally a vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [30]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>