<a href="https://colab.research.google.com/github/JaradAng/Classification-Project---Churn-Prediction/blob/main/00tensorflowfundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
###Going to explore tensor fundamentals using TF
# Going to go over:
# intro to tensors
# info from tensors
# manipulating tensors
# tensors and numpy
# using @tf.function to speed up python functions
#use GPU with TF
#Few exercises


# Into to tensors

In [16]:
#import TF
import tensorflow as tf
print(tf.__version__)

2.9.2


In [17]:
# creating a tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [18]:
#check number of dims of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [19]:
# Create vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [20]:
#Checking vector dimensions
vector.ndim

1

In [21]:
#Create a matrix(matrix has more than one dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [22]:
# checking dimensions of the matrix
matrix.ndim

2

In [23]:
# specify the dtype of matrix
another_matrix = tf.constant([[10., 7.],
                              [3.,2.],
                              [8.,9.]], dtype =tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [24]:
#checkin dimensions 
another_matrix.ndim

2

In [25]:
#creating a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [26]:
#check dims
tensor.ndim

3

What we created so far

* scalar : a single number
* Vector is a number with direction like wind speed and direction
* matrix is a 2-dimensional array of numbers
tensor is an n-dimensional array of numbers (where n can be anynumber, a 0-dimensinoal tensor is a scaler, 1-dimensional tensor is a vector)


In [27]:
#using the same tensor but with tf variable
changeable_tensor = tf.Variable([10,7])

unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [28]:
#Trying to change element in changeable tensor
# changeable_tensor[0] = 7

In [29]:
#Trying .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [30]:
#lets try on the unchangeable
# unchangeable_tensor[0].assign(7)

Unable to change if it is a constant. tf variable allows for a change

Note: Rarely will need to decide between the two but if in doubt use constant and change it later if needed

### next will be exploring random tensor creation. 

random tensors are some arbitrary size which contain random numbers


In [31]:
#Creating two (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # setting seed for reproducibility

random_1 = random_1.normal(shape=(3,2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [32]:
random_2 = tf.random.Generator.from_seed(42)

random_2 = random_2.normal(shape=(3,2))

random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [33]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of tensors elements

In [34]:
# Shuffle a tensor....valuable for when you want to shuffle your data so the inherent order doesn't effect learning

not_shuffled = tf.constant([[10, 7], [3,4], [2,5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [35]:
# shuffle the non shuffled tensor

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [36]:
# shuffle the non shuffled tensor
tf.random.set_seed(42) #Keeps the same order, global level seed

tf.random.shuffle(not_shuffled, seed= 42) #Still gets different results if did not have above becuase it is operation level

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Everytime running the shuffle, it puts it in a different order. If you want shuffle tensors to be in the same order, we have to use the global level random seed as well as operation level random seed

### Creating tensors in other ways

In [37]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [38]:
#Create tensor of all zeros
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors
the main difference between numpy arrasy and tf tensors is that tensors can be run on a gpu. which makes it much faster

In [39]:
# you can also turn Numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)

numpy_A

#X = tf.constant(some_matrix)  capital for matrix for tensor
#y = tf.constant(some_vector) lower case ususally a vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [40]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [41]:
B = tf.constant(numpy_A, shape = (2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

The shape must multiple together to equal the original shape of the numpy array

In [42]:
C = tf.constant(numpy_A, shape = (3,8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [43]:
A.ndim, B.ndim, C.ndim

(1, 3, 2)

### Getting information from tensors

* shape == tensor.shape
* size == tf.size(tensor)
* Axis or dims tensor[0] , tensor[:,1]
* Rank == tensor.ndim

In [44]:
#Create a rank 4 tensor

rank4_tensor = tf.zeros([2,3,4,5])

rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
rank4_tensor[0] # grabbing the first set of tensors

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [46]:
rank4_tensor.shape, rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [50]:
#get various attributes of our tensor

print('Datatype of every element:', rank4_tensor.dtype)

print('number of dimenensions(rank):', rank4_tensor.ndim)

print('Shape of tensor:', rank4_tensor.shape)

print('Elements along 0 axis:', rank4_tensor.shape[0])

print('Elements along last axis:', rank4_tensor.shape[-1])

print('Total number of elements:', tf.size(rank4_tensor).numpy())



Datatype of every element: <dtype: 'float32'>
number of dimenensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along last axis: 5
Total number of elements: 120


### Indexing Tensors

Tensors can be too big to see in the entirety. Need to be able to index

Tenors can be indexed just like python lists

In [51]:
#Get the first two elements of each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [52]:
#Get the first dimension from each index except the final one
rank4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

The first flatten but still have all five

In [53]:
#Get the first dimension from each index except the second to last
rank4_tensor[:1,:1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [55]:
#Create a rank 2 tensor
rank2_tensor = tf.constant([[10, 7], [3,4]])
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [57]:
# Get last item of each row of rank 2
rank2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [59]:
#Add in extra dim to rank2 tensor
rank3_tensor = rank2_tensor[...,tf.newaxis] # (...) include every axis until the last one

rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [60]:
#Alternative to tf.newaxis
tf.expand_dims(rank2_tensor, axis=-1) # -1 means to expland the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [61]:
tf.expand_dims(rank2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [62]:
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensors with basic operations

In [63]:
#You can add value to tensor using addtion
tensor = tf.constant([[10,7],[3,4]])

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [64]:
tensor + 10 # leaves the original unchanged unless you make it eqaul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [65]:
# Tensor multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [66]:
# Tensor subtraction
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [67]:
# using built in functions 
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [68]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [69]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [70]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

### Matrix multiplication

One of the most common tensor operations

In [71]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [72]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [74]:
tensor1 = tf.constant([[1,2,5],[7,2,1], [3,3,3]])
tensor1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [75]:
tensor2 = tf.constant([[3,5],[6,7],[1,8]])
tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [76]:
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [77]:
# using python operator @
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [78]:
tensor1.shape, tensor2.shape


(TensorShape([3, 3]), TensorShape([3, 2]))

Matrix size can not be the same will throw an error

### two rules tensors need to fulfill to be matrix multiply

1. inner dimensions must match 
2. the resulting matrix has the shape of the outter dimensions

when you get an error use tf.transpose so that the inner dimensions

### dot product

matrix multiplication is also known as dot product
use tf.matmul()
or tf.tensordot()

In [80]:
X = tf.constant([[1,2], [3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [83]:
#perform the dot product on tensor1 and tensor 2...
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [84]:
# Perform matrix multiplication between x and y
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [85]:
#Using reshape
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [86]:
#Check values of Y and transposed Y
print('normal Y:')

print(Y, '\n')

print('Y reshaped to (2,3): ')

print(tf.reshape(Y, (2,3)), '\n')

print('Y transposed')

print(tf.transpose(Y))

normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally when performing matrix multiplication on 2 tensors, and one of the axis do not line up. you will transpose it rather than reshape one of the tensors to match the inner numbers

---

### Chaning the dtype of tensors

default is 32 bit 
but we can use 16bit ie. float16

# mixed precision -- uses both in 16 bit adn 32 to help model preform faster


In [91]:
#Create new tensor with default dtype (float32)
B = tf.constant([1.7, 7.4])

B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [88]:
C = tf.constant([7,10])

C.dtype

tf.int32

In [92]:
#change from float 32 to float 16 called reduced procision 
D = tf.cast(B, dtype=tf.float16)

D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [93]:
#change int32 to float32
E = tf.cast(C, dtype=tf.float32)

E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)